#############################################################################
# Makefile for building: Raytracer
# Generated by qmake (2.01a) (Qt 4.8.5) on: Tue Feb 26 09:25:11 2013
# Project:  Raytracer.pro
# Template: app
# Command: d:\Development\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\bin\qmake -o Makefile Raytracer.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = d:\Development\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\bin\qmake
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: Raytracer.pro  ../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/default/qmake.conf ../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/device_config.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/qconfig.pri \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/modules/qt_webkit_version.pri \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/qt_functions.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/qt_config.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/win32-g++/qmake.conf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/win32-g++-4.6/qmake.conf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/exclusive_builds.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/default_pre.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/win32/default_pre.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/debug.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/debug_and_release.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/default_post.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/win32/default_post.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/win32/console.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/qt.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/uitools.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/win32/thread.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/moc.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/warn_on.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/win32/rtti.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/win32/exceptions.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/win32/stl.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/shared.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/resources.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/uic.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/yacc.prf \
		../../../Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/mkspecs/features/lex.prf \
		d:/Development/Tools/SDKs_APIs_Libraries/qt/qt-4.8-build_1-28-13/lib/QtUiToolsd.prl
	$(QMAKE) -o Makefile Raytracer.pro
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\device_config.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\qconfig.pri:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\modules\qt_webkit_version.pri:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\qt_functions.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\qt_config.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\win32-g++\qmake.conf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\win32-g++-4.6\qmake.conf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\exclusive_builds.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\default_pre.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\win32\default_pre.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\debug.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\debug_and_release.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\default_post.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\win32\default_post.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\win32\console.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\qt.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\uitools.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\win32\thread.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\moc.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\warn_on.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\win32\rtti.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\win32\exceptions.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\win32\stl.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\shared.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\resources.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\uic.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\yacc.prf:
..\..\..\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\mkspecs\features\lex.prf:
d:\Development\Tools\SDKs_APIs_Libraries\qt\qt-4.8-build_1-28-13\lib\QtUiToolsd.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile Raytracer.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
